[package]
name = "transport"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gd_udp = { path = "../gd_udp" }
protocol = { path = "../protocol" }
utils = { path = "../utils" }
hex = "0.4.3"